### PR TITLE
feat(location) : add zero outdegree node write exception

### PR DESCRIPTION
**Pull request by zhudaye12138**
Change-Id: I623522668344961d01ace8ea1a6b3f9c0b65a548

I think nodes without listeners should not be written. An exception should be thrown like this

 ```
  EZRNode<EZRSwitchedNodeTuple<id> *> *nodes = [node switchMap:^EZTuple2<id<NSCopying>,id> * _Nonnull(NSString * _Nullable next) {
        NSArray<NSString *> *components = [next componentsSeparatedByString:@"："];
        if (components.count > 1) {
            NSString *actorLines = [next substringFromIndex:components.firstObject.length + 1];
            return EZTuple(components.firstObject, actorLines);
        } else {
            return EZTuple(nil, next);
        }
    }];
    EZRNode<NSString *> *liLeiSaid = [nodes case:@"李雷"];
    [[liLeiSaid listenedBy:self] withBlock:^(NSString *next) {
        NSLog(@"李雷： %@", next);
    }];

    [node setValue:@"在一个宁静的下午" context:@"233333333"];
    node.value = @"李雷：大家好，我叫李雷。";
    node.value = @"韩梅梅：大家好，我叫韩梅梅。";  //error code, thrown exception
```

So I added a new exception type `EZRExceptionReason_CannotModifyZeroOutDegreeEZRMutableNode `

It is the responsibility of the user to check whether the node has outdegree.
If the user wants to set a value to the zero-outdegree node，I have provided a method `- (void)setLonelyValue:(id)value;`

EasyReact throwing this exception can help users make fewer mistakes in coding.

### CODE REVIEW

**Comment by WilliamZang** [comment]
Thanks for your contributing. It's nice code.

But when We designed EasyReact, we were going to let node as notify-subscribe mode:

Someone sets the node value whatever anyone listens, and someone listens the node value whatever anyone sets.

So I think differentiated processing set value isn't necessary. Sorry I can't merge this PR.

**Comment by zhudaye12138** [comment]
If you think differentiated processing set value isn't necessary.

Is it possible to throw a warning when setting value for no outdegree node?

In my opinion, setting value for no outdegree node is usually in the case of program exceptions.

Users don't necessarily understand memory management of easyreact

Code like this can confuse developers

```
    dispatch_queue_t queue = dispatch_queue_create("com.er.deliverQueue", DISPATCH_QUEUE_SERIAL);
    EZRMutableNode<NSNumber *> *oriNode = EZRMutableNode.new;
    NSObject *listener = [NSObject new];
    
    EZRNode<NSNumber *> *testNode = [oriNode deliverOnMainQueue];
    [[testNode listenedBy:listener] withBlock:^(NSNumber * _Nullable next) {
        NSLog(@"next = %@",next); //can not receive 2
    }];
    
    dispatch_time_t timer = dispatch_time(DISPATCH_TIME_NOW, 0.1 * NSEC_PER_SEC);
    dispatch_after(timer, queue, ^{
        oriNode.value  = @2; //want send 2 testNode
    });
```

Do you have a better way to solve this problem？  @WilliamZang

**Comment by face2d** [comment]
Too many concepts such as "zero outdegree" make the framework not easy to use. Even programmers are not easy to understand these mathematical concepts. Although graph theory is the guiding ideology of this framework, we pay more attention to the ease of use of the framework. Thanks for your contribution.

**Comment by WilliamZang** [comment]
Usually listener is self or something has long lifycycle. But giving a printing warning is ok.

But I think it's helpless if raise a warning when set value. Because you haven't known why listeners have gone and which the listeners are.

This is a good question.

**Comment by WilliamZang** [comment]
Sometimes nodes only are boxes whatevent anyone focus on them. Something nodes want to notify someone knows. Usecases always are varied.

**Comment by WilliamZang** [comment]
@zhudaye12138 If you like, you can print some warning within debug environment or other macro you defined.

**Comment by zhudaye12138** [comment]
@face2d  thanks, easy to use is more important
@WilliamZang   Did you mean I can PR this code？

```
- (void)setValue:(id)value context:(nullable id)context {
    if EZR_LikelyNO(!self.isMutable) {
        EZR_THROW(EZRNodeExceptionName, EZRExceptionReason_CannotModifyEZRNode, nil);
    }
    if EZR_LikelyNO(!(self.hasListener || self.hasDownstreamNode)) {
#if DEBUG
        NSLog(@"[EasyReact Warning] The node has no listeners");
#endif
    }
    [self next:value from:[EZRSenderList new] context:context];
}
```

**Comment by WilliamZang** [comment]
@zhudaye12138 Yes, like this:

```objective-c
- (void)setValue:(id)value context:(nullable id)context {
    if EZR_LikelyNO(!self.isMutable) {
        EZR_THROW(EZRNodeExceptionName, EZRExceptionReason_CannotModifyEZRNode, nil);
    }
#if DEBUG
    if EZR_LikelyNO(!(self.hasListener || self.hasDownstreamNode)) {
        NSLog(@"[EasyReact Warning] The node has no listeners");
    }
#endif
    [self next:value from:[EZRSenderList new] context:context];
}

```

**Pull request closed without merging**
